# Generated by Django 4.1.3 on 2022-12-19 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regritration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reg",
            name="Date_of_birth",
            field=models.DateField(
                default=datetime.datetime(2022, 12, 19, 12, 44, 50, 224267),
                verbose_name="Date",
            ),
        ),
    ]
