# Generated by Django 4.1.3 on 2022-12-21 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regritration", "0002_alter_reg_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reg",
            name="Date_of_birth",
            field=models.DateField(
                default=datetime.datetime(2022, 12, 21, 15, 19, 37, 746600),
                verbose_name="Date",
            ),
        ),
    ]
