# Generated by Django 4.1.3 on 2022-12-21 20:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("regritration", "0004_alter_reg_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="reg",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reg",
            name="Date_of_birth",
            field=models.DateField(
                default=datetime.datetime(2022, 12, 21, 21, 0, 58, 826246),
                verbose_name="Date",
            ),
        ),
    ]
